name: CI/CD ReactApp

on:
    push:
      branches: develop
 
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        node-version: [14.x]
    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 14.x to Build
      uses: actions/setup-node@v2
      with:
        node-version: 14.x
    - run: npm install
    - run: CI=false npm run build
    - name: Print Current Directory
      run: pwd

    - name: Debug DEPLOY_TARGET
      run: echo "DEPLOY_TARGET is ${{ secrets.DEPLOY_TARGET }}"
    - name: ssh deploy on aws ec2
      uses: easingthemes/ssh-deploy@v2.1.4
      env:
        SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
        REMOTE_HOST: ${{ secrets.EC2_HOST }}
        REMOTE_USER: ${{ secrets.EC2_USERNAME }}
        REMOTE_PORT: ${{ secrets.EC2_PORT }}
        SOURCE: "build/"
        TARGET: ${{ secrets.EC2_DEPLOY_TARGET }}