name: CI/CD React App

on:
  push:
    branches:
      - main

      
jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 14

      - name: Install Dependencies
        run: npm install

      - name: Build React App
        run: npm run build

      - name: Create Remote Directory
        run: ssh -i ${{ secrets.EC2_PRIVATE_KEY }} -p ${{ secrets.EC2_PORT }} ${{ secrets.EC2_USERNAME }}@${{ secrets.EC2_HOST }} "mkdir -p ${{ secrets.EC2_DEPLOY_TARGET }}"

      - name: SSH Deploy to AWS EC2
        uses: easingthemes/ssh-deploy@v2.1.4
        with:
          ARGS: -rltgoDzvO
        env:
          SSH_PRIVATE_KEY: ${{ secrets.EC2_PRIVATE_KEY }}
          REMOTE_HOST: ${{ secrets.EC2_HOST }}
          REMOTE_USER: ${{ secrets.EC2_USERNAME }}
          REMOTE_PORT: ${{ secrets.EC2_PORT }}
          SOURCE: "build/"
          TARGET: ${{ secrets.EC2_DEPLOY_TARGET }}
